// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS802X-su4HR1jSbKpsFTT2w09MBvRtOo',
    appId: '1:886241809412:web:d89257fba3ccb383d85151',
    messagingSenderId: '886241809412',
    projectId: 'math-ia-studio',
    authDomain: 'math-ia-studio.firebaseapp.com',
    storageBucket: 'math-ia-studio.firebasestorage.app',
    measurementId: 'G-T3LRDXNJ70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjcVk8I71Z_bH776Rn3OqKAkVRhlPrshU',
    appId: '1:886241809412:android:160e40d299b230d3d85151',
    messagingSenderId: '886241809412',
    projectId: 'math-ia-studio',
    storageBucket: 'math-ia-studio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLv7nlZVdeqJyBLgWZSGBEf9UHIKC936U',
    appId: '1:886241809412:ios:df852e7c10c6156dd85151',
    messagingSenderId: '886241809412',
    projectId: 'math-ia-studio',
    storageBucket: 'math-ia-studio.firebasestorage.app',
    iosBundleId: 'com.example.graficacionAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLv7nlZVdeqJyBLgWZSGBEf9UHIKC936U',
    appId: '1:886241809412:ios:df852e7c10c6156dd85151',
    messagingSenderId: '886241809412',
    projectId: 'math-ia-studio',
    storageBucket: 'math-ia-studio.firebasestorage.app',
    iosBundleId: 'com.example.graficacionAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS802X-su4HR1jSbKpsFTT2w09MBvRtOo',
    appId: '1:886241809412:web:1b5908a28ae5f22fd85151',
    messagingSenderId: '886241809412',
    projectId: 'math-ia-studio',
    authDomain: 'math-ia-studio.firebaseapp.com',
    storageBucket: 'math-ia-studio.firebasestorage.app',
    measurementId: 'G-9XCEWZ00YB',
  );
}
